######################################################################
# Automatically generated by qmake (3.0) Tue Jun 30 17:04:17 2020
######################################################################
QT       += core gui widgets
LIBS += -lv4l2 -lv4lconvert


TEMPLATE = app
TARGET = qt_v4l_camera_test
INCLUDEPATH += .

# Input
HEADERS += src/capturethread.h src/mainwindow.h src/videowidget.h
SOURCES += src/capturethread.cpp \
           src/main.cpp \
           src/mainwindow.cpp \
           src/videowidget.cpp
